### ISSUE TITLE
Deploy version 1.0.0

### ISSUE THREAD

**Issue by namkyu1999** [litmuschaos/backstage-plugin#11]
- [x] Resolve all issues
- [x] Add description
- [x] Update CONTRIBUTING.md
- [ ] Update Releases and Packages
- [x] Add DCO

**Comment by tudi2d** [comment]
Good job on this plugin - looks great!! Feel free to add yourself to the [Backstage Plugin Marketplace ](https://backstage.io/docs/plugins/add-to-marketplace) whenever you are ready to make it easier for the Backstage community to discover it! :)

**Comment by namkyu1999** [comment]
Sure :) I will add them after a few issues are resolved. Thanks for your comment @tudi2d!
