### ISSUE TITLE
Suggestion: Commit lockfile for stability

### ISSUE THREAD

**Issue by jongwooo** [litmuschaos/backstage-plugin#17]
I am wondering if we can commit a working `package-lock.json`(or `yarn.lock`) to the repo. Committing lockfiles to git is a [best practice](https://stackoverflow.com/a/76058921/802138) and the fact that there is no `package-lock.json` in the repo means that it might be broken for me when I check it out.

The problem is that the "latest versions" of npm packages change over time, so a semver range like `"pkg": "^8.0.0"` will resolve to different versions over time, i.e. instability.

**Comment by namkyu1999** [comment]
Hi, @jongwooo,
`yarn.lock` file is not the default setup in all backstage plugins. If you follow [this guide](https://backstage.io/docs/plugins/create-a-plugin), you can easily notice. But I don't know why. So can you take this issue?

**Comment by jongwooo** [comment]
@namkyu1999 [Backstage](https://github.com/backstage/backstage/blob/f1dc76bd9ab62249aa04230881d1480c14763c64/package.json#L43-L48) manages all plugins and packages as monorepo through [yarn workspaces](https://yarnpkg.com/features/workspaces). yarn workspaces use a single `yarn.lock` to manage the dependencies of all workspaces.

This repo doesn't use yarn workspaces, so I think it's okay to create a lockfile.

**Comment by namkyu1999** [comment]
Hey @jongwooo ,
Can you do this job? If not, I will update it later.

**Comment by jongwooo** [comment]
@namkyu1999 Sure:)
