### ISSUE TITLE
Support CI/CD

### ISSUE THREAD

**Issue by namkyu1999** [litmuschaos/backstage-plugin#7]
reference link: https://github.com/litmuschaos/litmus/tree/master/.github/workflows

**Comment by namkyu1999** [comment]
- Need to add GitHub Secret.
- Connect with npmjs

**Comment by jongwooo** [comment]
@namkyu1999 Can I work on this issue?

**Comment by namkyu1999** [comment]
Sure @jongwooo, Let me know the secrets you need to use after you raise a PR.

**Comment by RipulHandoo** [comment]
Hi @jongwooo, are you working on this? I'd like to collaborate with you on it.

**Comment by jongwooo** [comment]
Hi @RipulHandoo, I'd love to collaborate with you on it!
I've created a PR (#18) to remove some unused dependencies and migrate to yarn v3. The next steps are to make sure the `scripts` in `package.json` are working properly, and then to write a CI/CD workflow file.

**Comment by RipulHandoo** [comment]
Hey @jongwooo ,
I've successfully installed the backstage-plugin from the [litmuschaos/backstage-plugin](https://github.com/litmuschaos/backstage-plugin) repository. Could you please guide me on generating the API key for this particular setup?
Do i have to get it from [here](https://github.com/litmuschaos/litmus-ui).

**Comment by RipulHandoo** [comment]
Hey @jongwooo  @namkyu1999 
I've successfully set up the [Backstage_plugin](https://github.com/litmuschaos/backstage-plugin/)  but could use some guidance on configuring [Litmus](https://github.com/litmuschaos/litmus/).

**Comment by namkyu1999** [comment]
Hi @RipulHandoo, Here's a link

docs: https://docs.litmuschaos.io/docs/integrations/backstage

**Comment by RipulHandoo** [comment]
@namkyu1999 Just to be clear.
For generating API_Token I have to follow these [steps](https://docs.litmuschaos.io/docs/getting-started/installation) right?

**Comment by namkyu1999** [comment]
> @namkyu1999 Just to be clear. For generating API_Token I have to follow these [steps](https://docs.litmuschaos.io/docs/getting-started/installation) right?

right

**Comment by RipulHandoo** [comment]
Hi @namkyu1999, I am facing setup issues locally. Any alternative methods or suggestions? Also, is it advisable to start CI/CD without script verification?"

**Comment by RipulHandoo** [comment]
Hey @namkyu1999 @jongwooo 
I have successfully set up Litmus plugin, got LITMUS_AUTH_TOKEN, but facing "`Error: Missing required config value at 'app.baseUrl`" when starting Backstage. Attached `app-config.yaml `for reference.
![image](https://github.com/litmuschaos/backstage-plugin/assets/107461226/ab3b6012-b79e-4c41-9a3e-8f12b4739cd7)
